"""conversation belongs to the consumer

Revision ID: 1539ed052d21
Revises: 78b6ebe1a97d
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1539ed052d21'
down_revision: str | None = '78b6ebe1a97d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Разговор принадлежит тому, кто его ведёт. Копия переписки у нас была именно копией: для
    # работы агента она не использовалась ни разу, только для чтения ручкой. На десяти людях это
    # удобство, на тысяче — чужие переписки, за сохранность которых мы не обязаны отвечать.
    #
    # Вместо неё слот: последний вход и последний выход, перезаписываемые каждым ходом. Он спасает
    # результат от оборванного соединения и не превращается в журнал.
    #
    # Шаги уходят туда же: вызовы инструментов и их результаты теперь штатные события протокола —
    # потребитель получает их потоком и хранит у себя, если они ему нужны. Наша копия была бы
    # вторым журналом того же самого, и он бы разошёлся с первым.
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_steps_run_id'), table_name='steps')
    op.drop_table('steps')
    op.add_column('sessions', sa.Column('last_input', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('last_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_output')
    op.drop_column('sessions', 'last_input')
    op.create_table('steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ordinal', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tool', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('steps_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('steps_pkey'))
    )
    op.create_index(op.f('ix_steps_run_id'), 'steps', ['run_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('messages_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
