"""enums as enums

Revision ID: 28defbd4165b
Revises: c12972f9d472
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '28defbd4165b'
down_revision: str | None = 'c12972f9d472'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
