"""notes

Revision ID: 54641830423f
Revises: e5271a1c4876
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '54641830423f'
down_revision: str | None = 'e5271a1c4876'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('friction', name='notekind', native_enum=False, length=16), nullable=False),
    sa.Column('what', sa.Text(), nullable=False),
    sa.Column('where', sa.String(length=200), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_session_id'), 'notes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_session_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
