"""step tool and arguments

Revision ID: 78b6ebe1a97d
Revises: 0561b11926c9
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '78b6ebe1a97d'
down_revision: str | None = '0561b11926c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("steps", sa.Column("tool", sa.String(length=200), nullable=True))

    # Со значением по умолчанию НА ВРЕМЯ переливки: колонка обязательная, а строки в таблице уже
    # есть, и добавление без умолчания валит миграцию на первой же установке, где что-то писали.
    # Проверено: именно так она и упала.
    kind = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")
    op.add_column(
        "steps", sa.Column("arguments", kind, nullable=False, server_default=sa.text("'{}'"))
    )

    # Умолчание снимается сразу: дальше значение приходит из кода, и оставленное на месте
    # прикрывало бы пропуск, который мы хотели бы видеть.
    op.alter_column("steps", "arguments", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'arguments')
    op.drop_column('steps', 'tool')
    # ### end Alembic commands ###
