"""usage details

Revision ID: e5271a1c4876
Revises: 28defbd4165b
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e5271a1c4876'
down_revision: str | None = '28defbd4165b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('cache_creation_tokens', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('cache_read_tokens', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'duration_ms')
    op.drop_column('runs', 'cache_read_tokens')
    op.drop_column('runs', 'cache_creation_tokens')
    # ### end Alembic commands ###
